version: '3.9'

services:
  app:
    container_name: ads_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    depends_on:
      - ads_db

  ads_db:
    image: postgres:15.2
    container_name: ads_db_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.example


volumes:
  postgres_data: