version: '3.9'

services:
  ads_db:
    image: postgres:15.2
    container_name: ads_db_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env


volumes:
  postgres_data: